CREATE TABLE system_change_log (
    id INTEGER PRIMARY KEY NOT NULL,
    logdate timestamp(0),
    login CLOB,
    tablename CLOB,
    primarykey CLOB,
    pkvalue CLOB,
    operation CLOB,
    columnname CLOB,
    oldvalue CLOB,
    newvalue CLOB,
    access_ip CLOB,
    transaction_id CLOB, 
    log_trace CLOB,
    session_id CLOB,
    class_name CLOB,
    php_sapi CLOB,
    log_year varchar(4),
    log_month varchar(2),
    log_day varchar(2)
);
CREATE TABLE system_sql_log (
    id INTEGER PRIMARY KEY NOT NULL,
    logdate timestamp(0),
    login CLOB,
    database_name CLOB,
    sql_command CLOB,
    statement_type CLOB,
    access_ip varchar(45),
    transaction_id CLOB,
    log_trace CLOB,
    session_id CLOB,
    class_name CLOB,
    php_sapi CLOB,
    request_id CLOB,
    log_year varchar(4),
    log_month varchar(2),
    log_day varchar(2)
);
CREATE TABLE system_access_log (
    id INTEGER PRIMARY KEY NOT NULL,
    sessionid CLOB,
    login CLOB,
    login_time timestamp(0),
    login_year varchar(4),
    login_month varchar(2),
    login_day varchar(2),
    logout_time timestamp(0),
    impersonated char(1),
    access_ip varchar(45)
);
CREATE TABLE system_request_log (
    id INTEGER PRIMARY KEY NOT NULL,
    endpoint CLOB,
    logdate CLOB,
    log_year varchar(4),
    log_month varchar(2),
    log_day varchar(2),
    session_id CLOB,
    login CLOB,
    access_ip CLOB,
    class_name CLOB,
    http_host CLOB,
    server_port CLOB,
    request_uri CLOB,
    request_method CLOB,
    query_string CLOB,
    request_headers CLOB,
    request_body CLOB,
    request_duration INTEGER
);